### ISSUE TITLE
"Sepical Requirement" not recorded

### ISSUE THREAD

**Issue by azrfl** [azrfl/qrex#36]
![Image](https://user-images.githubusercontent.com/121843888/221727052-78303921-077e-4512-a2f0-d241c19c1977.png)
@azrafulazizi tlg tgkkn ni...factory dah pilih special requirement column test 'Handgard Inspection Method'

tp bila nk verified jd NA

![Image](https://user-images.githubusercontent.com/121843888/221727140-cdbeea95-17dc-44ef-a38a-3347c22331d5.png)

MCM NI

![Image](https://user-images.githubusercontent.com/121843888/221727196-b80710e8-57b0-4bbb-b737-698a161151be.png)

x de dlm list...tp dekat FG form by pallet tu ada je test name tu

**Comment by azrfl** [comment]
![image](https://user-images.githubusercontent.com/121843888/222035534-40cbfcc4-5076-4639-968f-73f89455c6d4.png)
try remove name for all option,Because system capture 1st value of option

**Comment by azrfl** [comment]
![image](https://user-images.githubusercontent.com/121843888/222035853-243d258f-8456-4402-8154-08c792988d47.png)

**Comment by azrfl** [comment]
N/A
OMT
Foaming
Rubbing
IPA/Alcohol
Physical Properties
Protein
Predictive Aging
Powder Content/Residue
Handgards Inspection Method
Metal Test
Mirror Test
Durability Test

Confirmed with Bazilah

Selection not appear in fg edit form and reinspect

**Comment by tgqadev** [comment]
Change at FG

![Image](https://user-images.githubusercontent.com/125102783/223904268-db5ca50c-cbdc-4cbe-9271-a54b7687359b.png)

**Comment by tgqadev** [comment]
Change at SFG


![Image](https://user-images.githubusercontent.com/125102783/223904393-4569f2bf-9ce9-4ee5-9a30-ea88cc18cae3.png)

**Comment by azrfl** [comment]
![Image](https://user-images.githubusercontent.com/121843888/223904539-0f814400-bd31-4118-b3a1-33325c1086e9.png)

**Comment by azrfl** [comment]
![Image](https://user-images.githubusercontent.com/121843888/223904628-745daa12-c713-4472-8eca-13a7ec0fd244.png)

**Comment by azrfl** [comment]
Rectification UAT


![Image](https://user-images.githubusercontent.com/121843888/223907639-c54023df-4d6c-497b-ba07-40c5b30de179.png)

Push Verify Button


![Image](https://user-images.githubusercontent.com/121843888/223907787-59b6fbe4-23b8-4901-9e39-6e103f01575c.png)

Reinspect button


![Image](https://user-images.githubusercontent.com/121843888/223907891-f0cab04d-5c90-422f-86bd-6b69de09d87f.png)
